### PR TITLE
Add fast-off for debug/trace

### PR DESCRIPTION
**Pull request by jcorbin**
r @rf @raynos

### CODE REVIEW

**Comment by rf** [comment]
off by default?

**Comment by jcorbin** [comment]
Correct, thoughts?

**Comment by rf** [comment]
I think debug and trace should be on by default. For most services, the overhead from debug/trace logs isn't a problem. There are some users of larch who would be surprised to have their debug/trace logs turned off by default when upgrading.

**Comment by jcorbin** [comment]
Makes sense, hyperbahn can explicitly call it.

**Comment by rf** [comment]
:+1: merge at will

**Pull request merged**
